default_platform(:ios)

DEVELOPER_APP_ID = ENV["DEVELOPER_APP_ID"]
DEVELOPER_APP_IDENTIFIER = ENV["DEVELOPER_APP_IDENTIFIER"]
PROVISIONING_PROFILE_SPECIFIER = ENV["PROVISIONING_PROFILE_SPECIFIER"]
TEMP_KEYCHAIN_USER = ENV["TEMP_KEYCHAIN_USER"]
TEMP_KEYCHAIN_PASSWORD = ENV["TEMP_KEYCHAIN_PASSWORD"]
APPLE_ISSUER_ID = ENV["APPLE_ISSUER_ID"]
APPLE_KEY_ID = ENV["APPLE_KEY_ID"]
APPLE_KEY_CONTENT = ENV["APPLE_KEY_CONTENT"]
GIT_AUTHORIZATION = ENV["GIT_AUTHORIZATION"]

def delete_temp_keychain(name)
  delete_keychain(
    name: name
  ) if File.exist? File.expand_path("~/Library/Keychains/#{name}-db")
end

def create_temp_keychain(name, password)
  puts "before creating keychain"
  create_keychain(
    name: name,
    password: password,
    default_keychain: true,
    unlock: true,
    lock_when_sleeps: false
  )
  puts "after creating keychain"
end

def ensure_temp_keychain(name, password)
  delete_temp_keychain(name)
  create_temp_keychain(name, password)
end

platform :ios do
  lane :closed_beta do
    puts "Close beta started"
    keychain_name = TEMP_KEYCHAIN_USER
    keychain_password = TEMP_KEYCHAIN_PASSWORD
    puts "Creds taken"
    ensure_temp_keychain(keychain_name, keychain_password)

    puts "Keychain ensured"
    api_key = app_store_connect_api_key(
      key_id: APPLE_KEY_ID,
      issuer_id: APPLE_ISSUER_ID,
      key_content: APPLE_KEY_CONTENT,            
      duration: 1200,            
      in_house: false
    )
    
    increment_build_number(xcodeproj: "NBackGame.xcodeproj")
    
    cocoapods(
      clean_install: true
    )

    match(
      type: 'appstore',
      app_identifier: "#{DEVELOPER_APP_IDENTIFIER}",
      git_basic_authorization: Base64.strict_encode64(GIT_AUTHORIZATION),
      readonly: true,
      keychain_name: keychain_name,
      keychain_password: keychain_password,
      api_key: api_key
    )

    build_app(workspace: "NBackGame.xcworkspace", scheme: "NBackGame")
    deliver(
      submit_for_review: true,
      automatic_release: true,
      overwrite_screenshots: true,
      force: true,
      submission_information: {
        export_compliance_uses_encryption: false,
        add_id_info_uses_idfa: false
      }
   )
    clean_build_artifacts

    # gym(
    #   configuration: "Release",
    #   workspace: "NBackGame.xcworkspace",
    #   scheme: "NBackGame",
    #   export_method: "app-store",
    #   export_options: {
    #     provisioningProfiles: { 
    #         DEVELOPER_APP_ID => PROVISIONING_PROFILE_SPECIFIER
    #     }
    #   }
    # )

    # pilot(
    #   apple_id: "#{DEVELOPER_APP_ID}",
    #   app_identifier: "#{DEVELOPER_APP_IDENTIFIER}",
    #   skip_waiting_for_build_processing: true,
    #   skip_submission: true,
    #   distribute_external: false,
    #   notify_external_testers: false,
    #   ipa: "./NBackGame.ipa"
    # )

    delete_temp_keychain(keychain_name)
  end
end