
devices([
  "iPhone 15 Plus",
 # "iPhone 8 Plus",
  "iPad Pro (12.9-inch) (6th generation)",
  "iPad Pro (12.9-inch) (2nd generation)"
])

scheme("FastlaneScreenshot")

clear_previous_screenshots(true)

override_status_bar(true)

skip_open_summary(true)

headless(true)

languages([
  "en-US", 
  "pl",
  "es-ES",
  "ko",
  "de-DE",
  "zh-Hans"
])