name: Dev flow
on:
  push:
    branches: [ dev ]
  workflow_dispatch:
jobs:
  deploy:
    name: Run tests
    runs-on: macOS-14
    steps:
      - name: check fastlane
        run: fastlane --version
      - name: Checkout repository
        uses: actions/checkout@v3
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.0'
      # - name: Test
      #   run: xcodebuild clean build test -project NBackGame.xcodeproj -scheme "NBackGame" -sdk iphonesimulator -destination "platform=iOS Simulator,OS=16.1,name=iPhone 14" ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO
      - name: Create PR to Stable
        uses: maierj/fastlane-action@v2.3.0
        with:
          lane: create_pr_to_stable
        env:
          GIT_AUTHORIZATION: '${{ secrets.GIT_AUTHORIZATION }}'
          COMMIT_MESSAGE: '${{ github.event.head_commit.message }}'
