name: Stable flow
on:
  push:
    branches: [ testNONE ]

  # Allows you to run this workflow manually from the Actions a tab
  workflow_dispatch:

jobs:   
  deploy:
    name: Deploying to Testflight
    runs-on: macOS-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '14.1'
#      - name: Build
#        run: xcodebuild clean build test -project NBackGame.xcodeproj -scheme "NBackGame" -sdk iphonesimulator -destination "platform=iOS Simulator,OS=15.2,name=iPhone 11" ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO
#      - name: Deploy to TestFlight
#        uses: maierj/fastlane-action@v1.4.0
#        with:
#          xcode-version: '14.1'
#          lane: deploy_to_testflight
#        env:
#          BUNDLE_ID: '${{ secrets.BUNDLE_ID }}'
#          APP_STORE_CONNECT_TEAM_ID: '${{ secrets.APP_STORE_CONNECT_TEAM_ID }}'
#          DEVELOPER_APP_ID: '${{ secrets.DEVELOPER_APP_ID }}'
#          DEVELOPER_APP_IDENTIFIER: '${{ secrets.DEVELOPER_APP_IDENTIFIER }}'
#          DEVELOPER_PORTAL_TEAM_ID: '${{ secrets.DEVELOPER_PORTAL_TEAM_ID }}'
#          FASTLANE_APPLE_ID: '${{ secrets.FASTLANE_APPLE_ID }}'
#          FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: '${{ secrets.FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD }}'
#          MATCH_PASSWORD: '${{ secrets.MATCH_PASSWORD }}'
#          GIT_AUTHORIZATION: '${{ secrets.GIT_AUTHORIZATION }}'
#          PROVISIONING_PROFILE_SPECIFIER: '${{ secrets.PROVISIONING_PROFILE_SPECIFIER }}'
#          TEMP_KEYCHAIN_PASSWORD: '${{ secrets.TEMP_KEYCHAIN_PASSWORD }}'
#          TEMP_KEYCHAIN_USER: '${{ secrets.TEMP_KEYCHAIN_USER }}'
#          APPLE_KEY_ID: '${{ secrets.APPLE_KEY_ID }}'
#          APPLE_ISSUER_ID: '${{ secrets.APPLE_ISSUER_ID }}'
#          APPLE_KEY_CONTENT: '${{ secrets.APPLE_KEY_CONTENT }}'
#          GIT_USERNAME: '${{ secrets.GIT_USERNAME }}'
#          GIT_EMAIL: '${{ secrets.GIT_EMAIL }}'
#          PR_BODY: '${{ github.event.head_commit.message }}'
#          ITMSTRANSPORTER_FORCE_ITMS_PACKAGE_UPLOAD: false
      - name: Bump stable xcode-version
        uses: maierj/fastlane-action@v1.4.0
        with:
          lane: bump_verion
#          lane: update_bump_stable_version
        env: 
          GIT_USERNAME: '${{ secrets.GIT_USERNAME }}'
          GIT_EMAIL: '${{ secrets.GIT_EMAIL }}'
     - name: Push changes to dev
       uses: maierj/fastlane-action@v1.4.0
       with:
         lane: push_new_stable_to_dev
       env:
         GIT_USERNAME: '${{ secrets.GIT_USERNAME }}'
         GIT_EMAIL: '${{ secrets.GIT_EMAIL }}'
